[package]
name = "object-system-prototyping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kamadak-exif = "0.5.5"
magic = "0.14"

[dependencies.serde]
version = "1.0"
features = ["derive"]